services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: servorax-db
    restart: always
    environment:
      POSTGRES_USER: luigui
      POSTGRES_PASSWORD: servorax_pass_2026
      POSTGRES_DB: servorax_db
    ports:
      - "5432:5432" # Para que DataGrip conecte vía SSH
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Tu API de FastAPI
  backend:
    build: 
      context: ./BarberPoleWebBackend # Ajusta esta ruta si es necesario
      dockerfile: Dockerfile
    container_name: servorax-api
    restart: always
    depends_on:
      - db
    environment:
      # Muy importante: Usamos 'db' como host porque Docker resuelve el nombre del servicio
      DATABASE_URL: postgresql://luigui:servorax_pass_2026@db:5432/servorax_db
    ports:
      - "8000:8000"

volumes:
  pgdata: # Tus datos persistentes